version: "3.0"
services:
  fractal:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '3001:80'
    volumes_from:
      - fractal