version: "3.0"
services:
  fractal:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - data-static:/usr/src/app/static-build

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '3001:80'
    volumes:
      - data-static:/usr/src/app/static-build
volumes:
  data-static: